import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Logger;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sql.DataSource;

 public class IOService {

	static Logger log = Logger.getLogger(IOService.class.getName());
	static Connection con = null;
	static final boolean doLog = true;// this value can be a static reference from a global configuration to turn log on/off in the entire app

	public static DataSource getDataSource() {
		DataSource ds = null;
		try {
			Context ctx = new InitialContext();
			ds = (DataSource) ctx.lookup("java:comp/env/jdbc/database");
			if(doLog) log.info("DataSource Created successfully");
		} catch (NamingException e) {
			if(doLog) log.severe("Unable to create DataSource : " + e.toString());
		}

		return ds;
	}

	public static Connection getConnection() {
		try {
			con = getDataSource().getConnection();
			if(doLog)  log.info("Connection Opened..");
		} catch (SQLException e) {
			if(doLog) log.severe("Unable to get Connection : " + e.toString());
		}
		return con;
	}

	public static PreparedStatement getStatement(String sql) {
		PreparedStatement preparedStatement = null;
		try {
			preparedStatement = getConnection().prepareStatement(sql);
			if(doLog) log.info("Preparing Statement..");
		} catch (SQLException e) {
			if(doLog) log.severe("Unable to Prepare Statement : " + e.toString());
		} catch (Exception ex) {
			if(doLog) log.severe("Error Preparing Statement : " + ex.toString());
		}
		return preparedStatement;
	}
	
	
	public static PreparedStatement getStatement(String sql, int autoGeneratedKeys) {
		PreparedStatement preparedStatement = null;
		try {
			preparedStatement = getConnection().prepareStatement(sql, autoGeneratedKeys);
			if(doLog) log.info("Preparing Statement..");
		} catch (SQLException e) {
			if(doLog) log.severe("Unable to Prepare Statement : " + e.toString());
		} catch (Exception ex) {
			if(doLog) log.severe("Error Preparing Statement : " + ex.toString());
		}
		return preparedStatement;
	}

	public static int executeStatement(PreparedStatement preparedStatement) {
		int es = -1;
		try {
			es = preparedStatement.executeUpdate(); // execute insert statement
			if(doLog) log.info("Executing Statement..");
		} catch (SQLException e) {
			if(doLog) log.severe("Error Executing Statement" + e.getMessage());
			es = -1;
		} catch (Exception e1) {
			if(doLog) log.severe("Error Executing Prepared Statement : " + e1.toString());
		} finally {
			if (preparedStatement != null) {
				Connection conn = null;
				try {
					conn = preparedStatement.getConnection();
					if(doLog) log.info("Connection Retrievd");
				} catch (SQLException e) {
					if(doLog) log.severe("Failed To Retrieve Connection : " + e.toString());
				}

				try {
					preparedStatement.close();
					if(doLog) log.info("Statement Closed");
				} catch (SQLException e) {
					if(doLog) log.severe("Error Closing Statement : " + e.toString());
				}

				if (conn != null) {
					try {
						conn.close();
						if(doLog) log.info("Connection Closed");
					} catch (SQLException e) {
						if(doLog) log.severe("Error Closing Connection : " + e.toString());
					}
				}
			}
		}
		return es;
	}
	